"""Publish an offline reference catalog without modifying the supplied images."""
import json
from catalog import ASSETS, ROOT

HTML=r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Odot · Art references</title><style>
:root{color-scheme:dark;--bg:#262724;--panel:#333530;--ink:#eee7d7;--muted:#c0b7a6;--line:#606353;--accent:#bdcb83}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 system-ui,sans-serif}main{max-width:1440px;margin:auto;padding:38px 28px}h1,h2,h3{font-family:Georgia,serif;font-weight:normal;line-height:1.2}h1{font-size:clamp(36px,5vw,62px);margin:10px 0}h2{margin-top:40px}p{max-width:76ch;color:var(--muted)}a{color:var(--accent);text-underline-offset:4px}.eyebrow{color:var(--accent);text-transform:uppercase;letter-spacing:.16em;font-size:12px}.filters{display:flex;flex-wrap:wrap;align-items:center;gap:12px;margin:24px 0}input,select,button{font:inherit;color:var(--ink);border:1px solid var(--line);background:var(--panel);padding:9px 12px;border-radius:6px}input{max-width:100%;min-width:0}button{cursor:pointer}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--accent);outline-offset:3px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.card{min-width:0;border:1px solid var(--line);border-radius:8px;overflow:hidden;background:var(--panel)}.card button{padding:0;width:100%;border:0;border-radius:0;text-align:left}.card svg{display:block;width:100%;aspect-ratio:1;background:#333430}.caption{padding:15px}.caption h3{font-size:23px;margin:0 0 6px}.caption small{color:var(--muted)}.links{display:flex;gap:14px;flex-wrap:wrap;padding:0 15px 16px;font-size:13px}.board{display:block;width:100%;border:1px solid var(--line);border-radius:8px}table{width:100%;border-collapse:collapse}th,td{padding:12px 10px;border-bottom:1px solid var(--line);text-align:left;overflow-wrap:anywhere}td{color:var(--muted)}dialog{width:min(1300px,94vw);max-height:94vh;background:var(--bg);color:var(--ink);border:1px solid var(--line);border-radius:8px;padding:20px;overflow:auto}dialog::backdrop{background:#000b}dialog header{display:flex;align-items:center;justify-content:space-between;gap:12px}dialog h2{margin:0}dialog svg{width:100%;max-height:77vh;display:block;margin-top:14px}[hidden]{display:none!important}code{overflow-wrap:anywhere}footer{margin-top:32px;color:var(--muted);font-size:13px}@media(max-width:1050px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){main{padding:24px 16px}.grid{grid-template-columns:minmax(0,1fr)}th,td{font-size:13px;padding:10px 5px}}
</style></head><body><main><div class="eyebrow">Reference library · Supplied art direction</div><h1>The next village.</h1><p>Village buildings, characters, and magical forest hex tiles from all five supplied reference sets. Open an image to inspect it at full size, or follow the links to the Blender source, render, and portable model.</p>
<div class="filters"><label for="search">Find an asset</label><input id="search" type="search" placeholder="Tower, berserker, tavern…"><label for="kind">Show</label><select id="kind"><option value="all">All references</option><option value="buildings">Buildings</option><option value="characters">Characters</option><option value="environment">Environment</option><option value="more_buildings">More buildings</option><option value="magical_forest">Magical forest</option><option value="autobattler">New autobattler set</option><option value="evil_autobattler">New evil units</option><option value="original">Original set</option></select><span id="count" role="status" aria-live="polite"></span></div><section class="grid" id="assets" aria-label="Art reference catalog"></section>
<h2>Reuse across the new set</h2><table><thead><tr><th>Components</th><th>Where they recur</th></tr></thead><tbody><tr><td>Blue tiles, limestone blocks, timber joinery</td><td>Both towers and the cottage workshops</td></tr><tr><td>Barrels, crates, lanterns, shrubs</td><td>Village and defensive buildings</td></tr><tr><td>Arrows, target, spears</td><td>Arrow tower and barracks</td></tr><tr><td>Books, mugs, benches, parcels</td><td>Academy, tavern, and market</td></tr><tr><td>Skulls and armor spikes</td><td>Evil unit faces, buckles, helmets, shoulders, and display props</td></tr><tr><td>Axe geometry and 19-bone character skeleton</td><td>Berserker equipment and the existing character set</td></tr></tbody></table><p><a href="../props/shared_village_kit.blend">Shared Blender prop library</a> · <a href="autobattler/manifest.json">Autobattler archive checksums</a> · <a href="evil_autobattler/manifest.json">Evil unit archive checksums</a></p>
<p><a href="../environment/shared_forest_kit.blend">Shared forest component library</a> · <a href="more_buildings/manifest.json">More building checksums</a> · <a href="magical_forest/manifest.json">Magical forest checksums</a></p><h2>Original reference board</h2><a href="fantasy_village.png"><img class="board" src="fantasy_village.png" alt="Original reference with tree house, bakery, mine, woodcutter, knight, mage, and archer" loading="lazy"></a><footer>The supplied PNGs are preserved byte for byte. The supplied images guide editable building models, characters, reusable forest parts, and assembled hex tiles. Optimization follows art review. This reference library works offline.</footer></main>
<dialog id="detail"><header><h2 id="title"></h2><button id="close">Close</button></header><svg id="full" role="img" aria-label="Full size art reference" preserveAspectRatio="xMidYMid meet"><image id="full-image"/></svg></dialog><script>
const assets=__ASSETS__, $=id=>document.getElementById(id);
for(const a of assets){const card=document.createElement('article');card.className='card';card.id=a.id;card.dataset.id=a.id;card.innerHTML=`<button aria-label="Inspect ${a.title} reference"><svg viewBox="${a.crop.join(' ')}" role="img" aria-label="Reference for ${a.title}"><image href="${a.reference}" width="${a.dimensions[0]}" height="${a.dimensions[1]}"/></svg><div class="caption"><h3>${a.title}</h3><small>${a.batch.replaceAll('_',' ')} · ${a.category==='characters'?'Character':a.category==='environment'?'Hex tile':'Building'}</small></div></button><div class="links"><a href="${a.reference}">Original PNG</a>${a.built?`<a href="../${a.category}/${a.id}.blend">Blender</a><a href="../../exports/previews/${a.id}.png">Render</a><a href="../../exports/${a.category}/${a.id}.glb">GLB</a>`:''}</div>`;card.querySelector('button').onclick=()=>{$('title').textContent=a.title;$('full').setAttribute('viewBox',a.crop.join(' '));$('full-image').setAttribute('href',a.reference);$('full-image').setAttribute('width',a.dimensions[0]);$('full-image').setAttribute('height',a.dimensions[1]);$('detail').showModal()};$('assets').append(card)}
function filter(){let visible=0;for(const a of assets){const kind=$('kind').value;const show=a.title.toLowerCase().includes($('search').value.trim().toLowerCase())&&(kind==='all'||a.category===kind||a.batch===kind);$(a.id).hidden=!show;if(show)visible++}$('count').textContent=visible+' references'}$('search').oninput=filter;$('kind').onchange=filter;$('close').onclick=()=>$('detail').close();filter();
</script></body></html>'''


def main():
    assets=[dict(a,built=all((ROOT/folder/a['category']/f"{a['id']}.{ext}").exists()
                            for folder,ext in [('sources','blend'),('exports','glb')])) for a in ASSETS]
    path=ROOT/'sources/reference/index.html'
    path.write_text(HTML.replace('__ASSETS__',json.dumps(assets)))
    print(path)


if __name__=='__main__': main()
